name = "Norma"
uuid = "b933802f-98f0-4369-86cc-558227202cec"
authors = ["Alejandro Mota <amota@sandia.gov>"]
version = "0.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Einsum = "b7d42ee7-0b51-5a75-98ca-779d3107e4c0"
Exodus = "f57ae99e-f805-4780-bdca-96e224be1e5a"
Format = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
DelimitedFiles = "1"
Einsum = "0.4"
Exodus = "0.14"
Format = "1"
IterativeSolvers = "0.9"
LinearAlgebra = "1"
Logging = "1"
NPZ = "0.4"
Printf = "1"
Random = "1"
SparseArrays = "1"
StaticArrays = "1"
Statistics = "1"
Symbolics = "6"
YAML = "0.4"
julia = "1"
